Investigate ingesting Open Street Maps
nestauk/ontologies pull request #15
Opened 2021-11-18 11:09 UTC by doogyb

closes #13

2021-11-18 11:13 UTC, doogyb commented
@mindrones I need to write a short script to automate the downloading of the zipped RDF files. Where in the dir structure should I put this script? My guess is:

```
ontologies
  OSM
    queries
      stress
        ...
      explore
        ...
    results
      stress
        ...
      explore
        ...
    bin
      fetch.js
...  
```

2021-11-18 11:36 UTC, mindrones commented
I'd say:

```
/ontologies
	OSM/
		queries/
      		stress/
			explore/
		results/
      		stress/
			explore/
	.../
/src
	bin
		OSM/
			fetch.js
		.../
	utils/
		...
```

2021-11-18 11:41 UTC, mindrones commented
We could have a `data` dir within each ontology dir so that e.g. `src/bin/OSM/fetch.js` would put the fetched data in `ontologies/OSM/data/*`:

```
I'd say:

```
/ontologies
	OSM/
		data/
		queries/
			stress/
			explore/
		results/
			stress/
			explore/
	.../
/src
	bin/
		OSM/
			fetch.js
		.../
	utils/
		...
```
```

2021-11-18 15:29 UTC, doogyb commented
I've left it for now, as the data won't be stored on the repo either way, and the script in question maintains the flexibility of being able to output the files to any given directory by supplying the path as an argument.

2021-11-18 16:51 UTC, mindrones requested changes
left some minor comments

2021-11-18 16:51 UTC, mindrones commented on package.json
> +{
we usually sort package.json keys alphabetically

2021-11-18 16:51 UTC, mindrones commented on package.json
> +    "sparql"
I'd sort these alphabetically

2021-11-18 16:51 UTC, mindrones commented on package.json
> +  "license": "ISC",
these two can go as we have a license in the repo

2021-11-18 16:51 UTC, mindrones commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Here we need to have an npm script that runs `src/bin/OSM/download_latest_lgd_releases.sh`

2021-11-24 17:06 UTC, mindrones requested changes
first pass

2021-11-24 17:06 UTC, mindrones commented on package.json
> +  "version": "1.0.0"
for now I'd set the version to `0.0.1`

2021-11-24 17:06 UTC, mindrones commented on src/bin/linkedGeoData/fetch.sh
> +if [ $# -ne 1 ] || [ ! -d $1 ]; then
I'd rename this to `fetchReleases.sh`

2021-11-24 17:06 UTC, mindrones commented on package.json
> +  },
I'd use `scripts` to run executables in `bin/`

```suggestion
  "scripts": {
	"lgdFetchReleases": "bash src/bin/linkedGeoData/fetchReleases.sh",
	"lgdFetchURLs": "node src/bin/linkedGeoData/fetchURLs.js"
  },
```

2021-11-24 17:06 UTC, mindrones commented on src/bin/linkedGeoData/fetch_urls.js
> +import fetch from 'node-fetch';
I'd rename to `src/bin/linkedGeoData/fetchURLs.js`

2021-11-24 17:06 UTC, mindrones commented on .eslintrc.yml
> +env:
I'd move this to `src/`

2021-11-24 17:06 UTC, mindrones commented on package.json
> +  "main": "index.js",
I'd remove `main` for now

2021-11-24 17:06 UTC, mindrones commented on package-lock.json
> +{
I'd run `npm install` in the root to make sure this is consistent with the changes in `package.json`

2021-11-25 11:00 UTC, mindrones approved these changes
Great, good to merge 👍

2021-11-25 11:05 UTC, mindrones commented
On second thought, I’d add `closes #17` to the commit message so we can get rid of #17 too!

2021-11-25 11:05 UTC, doogyb commented
closes #17

2021-11-25 11:20 UTC, merged

2021-11-25 11:23 UTC, doogyb commented
closes #17