33 automate uploading benchmarking results
nestauk/ontologies pull request #37
Opened 2021-12-20 12:52 UTC by doogyb

Script to upload the ntriples to a triplestore to allow for querying the benchmark metrics.

2021-12-20 14:03 UTC, mindrones requested changes
first pass

2021-12-20 14:03 UTC, mindrones commented on src/node_modules/queries/util.mjs
> +import * as path from 'path'
We usually use:

```suggestion
import path from 'path'
```

2021-12-20 14:03 UTC, mindrones commented on src/bin/benchmarking/uploadResults.mjs
> +	// remove http:// from string
I'd prefer to declare a `main` and invoking it explicitly

2021-12-20 14:03 UTC, mindrones commented on src/benchmarking/config.yml
> +    endpoint: "http://ec2-18-170-45-162.eu-west-2.compute.amazonaws.com:3000/sparql"
Is this duplicate of info we have in `src/node_modules/config.mjs`?

2021-12-20 14:03 UTC, mindrones commented on src/bin/benchmarking/uploadResults.mjs
> +	// remove http:// from string
These things could be precomputed in a file like `src/node_modules/configured.mjs` or so, that would import from `src/node_modules/config.mjs`, with everyone importing from one and/or the other depending on the circumstances.

This way we'd have computation happenning only once and in a single place.

2021-12-20 17:52 UTC, doogyb commented on src/benchmarking/config.yml
> +    endpoint: "http://ec2-18-170-45-162.eu-west-2.compute.amazonaws.com:3000/sparql"
Yes, but seeing as the Iguana tool imports this directly, I'm not sure how to merge the `config.mjs` with `config.yml`... Unless we generate this file dynamically? Which seems overkill. I could be overengineering this though

2021-12-22 16:32 UTC, mindrones approved these changes
GTM apart from some double quotes here and there, that I'd change with single quotes

2021-12-23 09:58 UTC, merged